### ISSUE TITLE
File-drop UI updates

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8-rebuild-file-drop#16]
File-Drop UI improvements to make it look more professional:

- fix some workflow issues (like the fact that it doesn't support dropping when results are being shown (the user needs to click on the 'reload icon')
- add help
- add sample files links
- add threat analysis (see what the Glasswall Desktop did)

**Comment by GINAGC** [comment]
@MaNe2020 please do some testing to this app: http://ec2-3-12-120-0.us-east-2.compute.amazonaws.com/ (no login required, just hit enter) and please comment on the UI issues that we should fix. Thanks

**Comment by MaNe2020** [comment]
@GINAGC 
Login page: Link to "terms of use" is not working, but this is really minor.
More importantly, I tried importing pdf file, the type was incorrect and file was marked as cleaned.
I did the same on filedrop.co.uk and the results do not match. 

![image](https://user-images.githubusercontent.com/70108899/102667543-e8621880-4189-11eb-900a-615229cb81f6.png)

**Comment by MaNe2020** [comment]
@GINAGC and since you said UI

- The website is not responsive. So if you half the screen you see just half of it and you cannot scroll anyway.
- Not sure if this is work in progress but having just an option to download analysis report, does not have any value, so it should definitely have option to download clean file, and maybe even not just download but maybe even see it directly on the website.
- I would add also option to have some history of uploads. Like previously uploaded/cleaned file. Being on the left side menu.
- In general more options that will make this personalized (that is what should make it different from https://file-drop.co.uk/)

**Comment by GINAGC** [comment]
@MaNe2020 my URL above was not correct, the version that we will focus on is Kubernetes, which is http://3.133.161.191/ - so please check that one when possible, we are not going to do many fixes in this initial PoC.

**Comment by MaNe2020** [comment]
@GINAGC in that case maybe add just:
- History tab in left side menu (previous uploads) - it can be just a placeholder at the moment but it would be great to see more things going on, on the UI, except bare minimum.
- More options when navigated to user (at the moment just log out and change password)
![tt](https://user-images.githubusercontent.com/70108899/102756644-8283b580-4370-11eb-80c2-4e6c9975f4d6.png)

- Some short description below GLASSWALL REACT APP (few details about it)
- Add links to architecture or APIs
